side-project-drrr/frontend

component/src/stories/navbar/NavbarComponent.stories.ts, component/src/stories/navbar/NavbarComponent.tsx
=>  design: sidebar storybook 생성

component/.storybook/main.ts, component/src/stories/Input/SearchInput.tsx, component/src/stories/stackTable/StackTable.stories.ts, component/src/stories/stackTable/StackTable.tsx, component/src/stories/stackTable/stackDummy.ts, component/src/stories/table/TablePage.tsx
stack 여부 판단하는 input을 dropdown으로 변경하게 되었으며 그로 인해 dropdown으로 만듬
=>  storybook: stack table dropdown으로 변경됨에 따라 dropdown

component/src/stories/table/TablePage.tsx, component/src/stories/table/data.ts, component/src/stories/table/selectData.ts
=>  feature: author filter search 완료

component/src/stories/table/Stack.ts, component/src/stories/table/TablePage.tsx, component/src/stories/table/data.ts
=>  feature: Table Stack select을 이용한 검색 기능

admin/tests/table.test.ts, service/tests/Add.tsx
=>  test: 검색 항목 test code 작성중

component/src/stories/preference/PreferenceTab.tsx, component/src/stories/preference/preferenceTab.stories.ts, component/src/stories/preferenceModal/PreferenceModal.tsx, component/src/stories/preferenceModal/preferenceModal.stories.ts
=> design: 메인 콘텐츠 영역 선호도 탭 디자인 완료

service/src/pages/SignUpPrivacyPage.tsx
소셜 로그인 후 개인정보 입력 form 이메일 형식 validation 완료
=> feature: 소셜 로그인 후 개인정보 입력 form 이메일 형식 validation 완료

component/src/stories/category/Calendar.stories.ts, component/src/stories/category/Category.tsx, component/tailwind.config.js, package.json, service/src/pages/SignUpPage.tsx
=>  design: 카테고리 선택 디자인 1차 완료

component/src/stories/category/Category.tsx, component/src/stories/login/LoginPage.tsx, component/src/stories/preference/PreferenceTab.tsx, service/src/App.tsx, service/src/components/social/kakao/KaKaoCallback.tsx, service/src/components/social/kakao/SocialKaKao.tsx, service/src/mocks/handlers.ts, service/src/pages/CategoryPage.tsx, service/src/pages/MainPage.tsx, service/src/pages/SignUpPage.tsx
카카오 로그인 기능 구현
백엔드와 테스트 완료
msw 테스트 완료
=>  feature: kakao login 구현 완료(백엔드 테스트 및 msw 테스트 완료)

service/src/App.tsx, service/src/components/service/SocialService.ts, service/src/components/social/github/GithubCallback.tsx, service/src/components/social/github/SocialGithub.tsx, service/src/components/social/kakao/KaKaoCallback.tsx, service/src/components/social/kakao/SocialKaKao.tsx
소셜 로그인 1차 리팩토링
추후 다른 http통신 시에 리팩토링 한번 더 할 예정
=>  refactor: 소셜 로그인 리팩토링 진행

service/src/pages/SignUpPage.tsx
이메일 1차 완료
프론트에서 이메일 입력 후 인증하기 -> (이메일 형식 체크) -> 백엔드로 이메일 전송
백엔드에서 준 인증번호 코드 -> 다시 백엔드로 전송 하는 형식으로 구현 완료
추후 백엔드와 이야기 후 조정 예정
=>  feature: 이메일 인증 1차 완료

component/src/stories/login/LoginPage.tsx, service/src/components/social/SocialCallback.tsx, service/src/mocks/handlers.ts, service/src/pages/SignUpPage.tsx
=>  feature: msw를 이용한  회원가입 완료

service/src/mocks/handlers.ts, service/src/pages/SignUpPage.tsx
refactor: 이메일 인증 api url 변경으로 인한 수정
=> refactor: 이메일 인증 api url 변경으로 인한 수정

service/src/pages/SignUpPage.tsx
=>  feature: 이메일 인증 타이머 기능 구현

component/src/index.css, component/src/stories/header/NoAuthHeader.tsx, service/src/components/aside/Aside.tsx, service/src/components/category/CategoryList.tsx, service/src/components/layout/Layout.tsx, service/src/index.css, service/src/pages/MainPage.tsx
main page 디자인 배치 및 google font 적용
=>  design: main 디자인 배치

component/src/index.css, component/src/stories/listbox/Listbox.stories.ts, component/src/stories/listbox/Listbox.tsx, component/src/stories/listbox/index.ts, service/src/pages/MainPage.tsx, tsconfig.json
=> Storybook: 코드리뷰를 통항 리팩토링 및 수정 

service/src/pages/MainPage.tsx, service/src/service/PushService.ts, service/src/webpush/main.ts, service/src/webpush/sw.js
=>  feature: web push 구현 중

service/src/components/aside/Aside.tsx, service/src/components/aside/TopKeywords.tsx, service/src/components/aside/type.ts, service/src/mocks/handlers.ts, service/tailwind.config.cjs
=>  feature: 메인 페이지 탑 키워드 뽑아오기

service/src/components/aside/TopKeywords.tsx, service/src/pages/MainPage.tsx, service/src/service/TopKeyword.ts
기존에 있던 topkeyword msw 코드를 local 환경에서 백엔드 데이터를 받아와서 보여주도록 테스트 진행
=>  feature: msw -> http 연동 topkeyword 받아오기 완료

service/src/App.tsx, service/src/components/aside/TopPost.tsx, service/src/pages/MainPage.tsx, service/src/service/TopPostService.ts
=>  feature: topPost local 백엔드 완료

service/src/pages/KeywordPage.tsx
1. 검색 결과 값 없을 때 no result 표시
2. debounce를 이용한 호출지연
- api 호출은 초기에 한번만 하고 가지고 있는 값들과 input에 입력된 값을 비교하여 검색 값을 보여주는 방식
=> feat: search with debounce and show no result

component/src/stories/header/Header.tsx, service/src/components/layout/Layout.tsx, service/src/hooks/useTokenDecode.tsx, service/src/pages/MainPage.tsx, service/src/repository/AuthRepository.ts, service/src/service/CategoryService.ts, service/src/service/auth/SocialService.ts
사용자 카테고리에서 token이 없는 상태에서 api 호출 막기
=>  fix: 사용자 카테고리에서 token이 없는 상태에서 api 호출 막기

component/src/index.css, component/src/stories/header/Header.tsx, component/src/stories/listbox/ListboxItem.tsx, service/src/App.tsx, service/src/ThemeContext/ThemeProvider.tsx, service/src/components/aside/TopPost.tsx, service/src/components/carousel/Carousel.tsx, service/src/components/layout/Layout.tsx, service/src/index.css, service/src/recoil/atom/darkModeState.ts, service/tailwind.config.cjs
=>  design: tailwind darkmode 구현

service/src/components/aside/TopPost.tsx, service/src/components/aside/type.ts, service/src/service/CategoryService.ts, service/src/service/TechBlogService.ts, service/src/service/TopKeyword.ts, service/src/service/TopPostService.ts, service/src/service/auth/SocialService.ts
백엔드 api url및 reponse data 수정으로 인한 코드 수정
=> refactor: 백엔드 api 수정에 따른 코드 수정

service/src/App.tsx, service/src/components/layout/Layout.tsx, service/src/components/layout/LayoutWIthAside.tsx, service/src/components/layout/LayoutWIthOutAside.tsx
=> feat: aside없는 페이지를 위해 레이아웃 분기

component/src/stories/listbox/ListboxItem.tsx
=>  design: darkmode design 적용

component/src/stories/login/Login.tsx, service/src/components/carousel/CategorySlide.tsx, service/src/components/modal/CategoryModal.tsx, service/src/components/modal/UserCategoryModal.tsx, service/src/pages/MainPage.tsx, service/src/recoil/atom/loginModalState.ts, service/src/repository/ProfileimgRepository.ts
=> design: 메인 페이지 사용자 선호 카테고리 영역 디자인 수정

service/src/components/recommend/Recommend.tsx
=>  review: 추천 게시글 랜덤으로 보여주는 코드 재 구현

service/src/service/UserProfileService.ts
=>  feature: 사용자 정보 api 반환 코드 추가

.github/workflows/main.yml, Dockerfile, nginx/nginx.conf
github actions를 활용한 docker images docker hub push test
=>  ci: github actions를 활용한 docker images docker hub push test

.github/workflows/main.yml
=> ci: git submodule error 수정

.github/workflows/main.yml, .yarnrc.yml
=> ci: yarn install error 수정

nginx/nginx.conf
Reverts side-project-drrr/frontend#131
=> Revert "docs: nginx healthcheck 경로 추가"

.github/workflows/main.yml, src/apis/HttpClient.tsx
ci: yml env production script 실행
=>  ci: yml env production script 실행

src/apis/HttpClient.tsx
=> env: 파일 변경 및 테스트

.dockerignore, .github/workflows/main.yml
ci: yarn install cache and docker image cache를 이용한 빌드 시간 단축 테스트
=>  ci: yarn install cache and docker image cache를 이용한 빌드 시간 단축 테스트

.github/workflows/main.yml, Dockerfile
ci: github actions run error 수정
=>  ci: github actions run error 수정

.github/workflows/main.yml
ci: github actions width -> with error 수정
=>  ci: github actions width -> with error 수정

.github/workflows/main.yml
ci: github actions docker image cache
=>  ci: github actions docker image cache

.github/workflows/main.yml, Dockerfile
ci: github actions yarn install cache error
=>  ci: github actions yarn install cache error

src/apis/HttpClient.tsx
=>  ci: docker cache test

.github/workflows/main.yml
ci: yarn install cache secound test
=>  ci: yarn install cache secound test

.github/workflows/main.yml
ci: yarn install cache error test
=>  ci: yarn install cache error test

.github/workflows/main.yml
ci: yarn install cache cypress error test
=>  ci: yarn install cache cypress error test

.github/workflows/main.yml
ci: yarn install cache cypress error test3
=>  ci: yarn install cache cypress error test3

.github/workflows/main.yml
ci: yarn install cache cypress error test4
=>  ci: yarn install cache cypress error test4

.github/workflows/main.yml, src/components/errors/ToManyRequestError.tsx
=>  feature: yml 주석 및 env 파일 수정

.github/workflows/main.yml
feature: gitgub actions env 파일 생성
=> feature: gitgub actions env 파일 생성

nginx/nginx.conf, src/components/social/SocialLogin.tsx, src/pages/MainPage.tsx, src/service/TechBlogService.ts, src/stories/listbox/ListboxItem.tsx
=>  feature: nginx 수정

src/pages/MainPage.tsx, src/service/TechBlogService.ts
=>  env: env production 파일 생성

nginx/nginx.conf
=>  refactor: nginx 파일 수정

src/components/card/CardComponent.tsx, src/components/card/CardList.tsx, src/components/card/type.ts, src/components/conditionalrenderer/ConditionalRenderer.tsx, src/components/recommend/Recommend.tsx, src/components/recommend/type.ts, src/pages/MainPage.tsx, src/recoil/atom/HeaderSearchDataState.ts, src/recoil/atom/techBlogData.ts, src/recoil/atom/techBlogDataState.ts, src/service/TechBlogService.ts, src/stories/listbox/Listbox.tsx, src/stories/listbox/ListboxItem.tsx, src/stories/listbox/type.ts
전체 기술 블로그 데이터 useState -> useRecoilState 변경
card ComPonent link 기능 등.. 추가
=>  fix: 좋아요 기능 api 과다 호출 개선 및 기능 수정

src/pages/HeaderSearchPage.tsx, src/stories/listbox/Listbox.stories.ts
=>  fix: build 중 error 수정

src/context/UserProfile.tsx
feature: userProflie api 호출 수정
=>  feature: userProflie api 호출 수정

.github/workflows/main.yml
refactor: production script 수정으로 인한 github actions 수정
=>  refactor: production script 수정으로 인한 github actions 수정

src/App.tsx, src/components/card/CardComponent.tsx, src/components/recommend/Recommend.tsx, src/context/UserProfile.tsx, src/pages/MainPage.tsx, src/stories/listbox/ListboxItem.tsx
=>  fix: 개발자 모드에서 warning 제거

src/components/aside/TopKeywords.tsx, src/components/modal/CategoryModal.tsx, src/components/modal/UserCategoryModal.tsx, src/components/social/SocialCallback.tsx, src/pages/MainPage.tsx, src/stories/listbox/ListboxItem.tsx
=> refator: api 중복 수정

src/stories/listbox/ListboxItem.tsx
voc-9: 좋아요 클릭 시 실시간 좋아요 수 반영 구현
=> voc-9: 좋아요 클릭 시 실시간 좋아요 수 반영 구현
